MVCPractice/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;
using System.Net.Http;
using System.Net.Http.Headers;
using MVCPractice.Models;



namespace MVCPractice.Controllers
{
    public class CustomerController : Controller
    {
        //
        // GET: /Customer/

        public ActionResult Index()
        {
            List<accountDetailViewModel> obj = new List<accountDetailViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                //HTTP GET
                var responseTask = client.GetAsync("BankApiNew/api/Customer/getAccountsOfUser?loginId="+Session["userId"].ToString());
                responseTask.Wait();


                
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<accountDetailViewModel>>();
                    readTask.Wait();



                    obj = readTask.Result;
                }
                else 
                {
                  
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
               

            Session["medal"] = null;
            return View(obj);
        }



        [HttpPost]
        public ActionResult Index(string selectedAccount)
        {
            if (string.IsNullOrEmpty(selectedAccount))
            {
                return RedirectToAction("Index");
            }
            else
            {
                Session["accountNumber"] = selectedAccount;
                int selectedAccount2 = int.Parse(selectedAccount);
                BankEntities2 dbContext = new BankEntities2();
                Account account = dbContext.Accounts.Single(x => x.accountNo == selectedAccount2);
                var amount = account.amount;
                CustomerMedal cmedal = dbContext.CustomerMedals.Single(x => amount > x.min && amount < x.max);
                Session["medal"] = cmedal.type;
                return RedirectToAction("Menu");
            }



        }



        public ActionResult Menu()
        {
            if (Session["accountNumber"] != null)
            {
                long accountNo = long.Parse((Session["accountNumber"]).ToString());
                BankEntities2 dbContext = new BankEntities2();
                Account account = (Account)(dbContext.Accounts.Single(x => x.accountNo == accountNo));

               
                return View(account);
            }
            else
            {
                return View("Index");
            }


        }



        public ActionResult FundTransfer()
        {
            return View();
        }



        [HttpPost]
        public ActionResult FundTransfer(long destinationAccountNo, int amount, string comment)
        {
            long accountNo = long.Parse(Session["accountNumber"].ToString());
            try
            {



                CustomerClass obj = new CustomerClass();
                TransactionClass obj1 = new TransactionClass();
                if (accountNo == destinationAccountNo)
                {
                    ViewBag.Error = "Source and destination account cant be same";
                    return View();
                }
                bool res = obj.checkAccount(destinationAccountNo);



                if (res)
                {
                    int amt = obj.getAmount(accountNo);
                    if (amt > amount)
                    {
                        obj.transferAdd(amount, destinationAccountNo);
                        obj.transferSub(amount, accountNo);



                        ViewBag.Success = "transferred " + amount + " successfully";



                        obj1.insTrans(accountNo, destinationAccountNo, amount, "FundTransfer", comment);
                        ModelState.Clear();
                    }
                    else
                    {
                        ViewBag.Error = "Insufficient Amount";
                    }
                }
                else
                {
                    ViewBag.Error = "Destination Account not found";
                }
            }



            catch (Exception exp)
            {
                ViewBag.Error = "Exception " + exp;
            }
            return View();
        }



        public ActionResult MiniStatement()
        {
            long accountNo = long.Parse((Session["accountNumber"]).ToString());
            BankEntities2 dbContext = new BankEntities2();



            List<Transaction> transactions = (List<Transaction>)(dbContext.Transactions.Where(x => x.fromAccountNo == accountNo || x.toAccountNo == accountNo).OrderByDescending(x => x.transactionId).ToList());



            return View(transactions);
        }



        [HttpPost]
        public ActionResult MiniStatement(DateTime fromDate, DateTime toDate)
        {
            CustomerClass obj = new CustomerClass();
            int accountNo = Int32.Parse((Session["accountNumber"].ToString()));
            IList<Transaction> transactions = obj.customstatement(accountNo, fromDate, toDate);
            if (transactions.Count == 0)
            {
                ViewBag.message = "No transactions found from " + fromDate + " to " + toDate;
                return View();
            }
            else
            {
                ViewBag.message = "Transactions  from " + fromDate + " to " + toDate;
            }
            ModelState.Clear();
            return View(transactions);



        }




        public ActionResult ChangePassword()
        {
            return View();
        }



        [HttpPost]
        public ActionResult ChangePassword(string oldPassword, string newPassword1, string newPassword2)
        {
            CustomerClass obj = new CustomerClass();
            bool success;
            ViewBag.message = obj.changePassword(oldPassword, newPassword1, newPassword2, Session["userid"].ToString(), out success);
            if (success)
                ModelState.Clear();
            return View();
        }



        public ActionResult BalanceEnquiry()
        {
            long accountNo = long.Parse((Session["accountNumber"]).ToString());
            BankEntities2 dbContext = new BankEntities2();
            Account account = (Account)(dbContext.Accounts.Single(x => x.accountNo == accountNo));
            return View(account);
        }



        public ActionResult CustomStatement()
        {
            return View();
        }



        //[HttpPost]
        //public ActionResult CustomStatement(DateTime fromDate,DateTime toDate)
        //{
        //    CustomerClass obj = new CustomerClass();
        //    int accountNo=Int32.Parse(( Session["accountNumber"].ToString()));
        //    IList<Transaction> transactions=obj.customstatement(accountNo,fromDate,toDate);




        //    return View("customStatementTable",transactions);



        //}
    }
}

MVCPractice/Controllers/SuperManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;
using System.Net.Http;
using MVCPractice.Models;

namespace MVCPractice.Controllers
{
    public class SuperManagerController : Controller
    {
        public ActionResult Index()
        {
            List<userDetailViewModel> allManagers = new List<userDetailViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.GetAsync("BankApiNew/api/SuperManager/getAllManagers");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<userDetailViewModel>>();
                    readTask.Wait();
                    allManagers = readTask.Result;
                }
                if (Session["mgrId"] != null)
                {
                    Session["mgrId"] = null;
                    
                }
                return View(allManagers);
            }
        }

        public ActionResult ManagersList()
        {
            List<userDetailViewModel> allManagers = new List<userDetailViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.GetAsync("BankApiNew/api/SuperManager/getAllManagers");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<userDetailViewModel>>();
                    readTask.Wait();
                    allManagers = readTask.Result;
                }
                if (Session["mgrId"] != null)
                {
                    Session["mgrId"] = null;

                }
                return View(allManagers);
            }
        }

        public ActionResult ManageManager()
        {
            return View();
        }

        [HttpPost]

        public ActionResult ManageManager(int managerId)
        {
            
            userDetailViewModel singleManager = new userDetailViewModel();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.GetAsync("BankApiNew/api/SuperManager/getSingleManager?managerId="+managerId);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<userDetailViewModel>();
                    readTask.Wait();
                    singleManager = readTask.Result;
                    ViewBag.mgrId = managerId; 
                }
                else
                {
                    ViewBag.NotFoundManager = "Manager Not Found";
                    return View("ManageManager");
                   
                }
                if (Session["mgrId"] != null)
                {
                    Session["mgrId"] = null;

                }
                return View(singleManager);
            }
        }
        public string getBranchId(int managerId)
        {

            string singleManager="";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.GetAsync("BankApiNew/api/SuperManager/getBranchId?managerId=" + managerId);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<string>();
                    readTask.Wait();
                    singleManager = readTask.Result;
                }
                if (Session["mgrId"] != null)
                {
                    Session["mgrId"] = null;

                }
                ViewBag.mgrId = managerId;
               
            }
            return singleManager;
        }

        public ActionResult AddManager()
        {
            List<branchDetailViewModel> branchList=new List<branchDetailViewModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.GetAsync("BankApiNew/api/SuperManager/getUnassignedBranch");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<branchDetailViewModel>>();
                    readTask.Wait();
                    branchList = readTask.Result;
                }
               
                
            }
            return View(branchList);
        }

         [HttpPost]
        public ActionResult AddManager(string name, string gender,DateTime dateOfBirth,string address,string state,string city,int pincode,string mail,string branch, string phoneNumber)
        {
        
             
            userDetailViewModel addManagerDetails = new userDetailViewModel
            {
                userName = name,
                gender=gender,
                dateOfBirth=dateOfBirth,
                address = address,
                state=state,
                city=city,
                pincode=pincode,
                branchId = branch, 
                phoneNumber = phoneNumber,
                emailId = mail,
                createdDate=DateTime.Now,
                editedDate=DateTime.Now,
                managerId=999,
                createdBy=999,
                editedBy=999
            };
          
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.PostAsJsonAsync("BankApiNew/api/SuperManager/addManager", addManagerDetails);
                responseTask.Wait();
                var result = responseTask.Result;
                ViewBag.result = responseTask.Result;
            }
              
            
            return RedirectToAction("Index");
        }

        
        public ActionResult EditManager(int id)
         {
             ViewBag.mgrId = id;
             Session["mgrId"] = id;
         
             userDetailViewModel singleManager = new userDetailViewModel();
             using (var client = new HttpClient())
             {
                 client.BaseAddress = new Uri("http://localhost:80");
                 var responseTask = client.GetAsync("BankApiNew/api/SuperManager/getSingleManager?managerId=" + id);
                 responseTask.Wait();
                 var result = responseTask.Result;
                 if (result.IsSuccessStatusCode)
                 {
                     var readTask = result.Content.ReadAsAsync<userDetailViewModel>();
                     readTask.Wait();
                     singleManager = readTask.Result;
                 }
             }
            Session["oldEmailId"]=singleManager.emailId;
            Session["oldBranchId"]=singleManager.branchId;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.GetAsync("BankApiNew/api/SuperManager/getUnassignedBranch");
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<branchDetailViewModel>>();
                    readTask.Wait();
                    ViewBag.branchList = readTask.Result;
                }


            }

            return View(singleManager);
         }

        [HttpPost]
        public ActionResult EditManager(string name, string gender, DateTime dateOfBirth, string address, string state, string city, int pinCode,  string branch, string phoneNumber)
        {
            int userId = (int)Session["mgrId"];
            string oldBranchId = Session["oldBranchId"].ToString();
            string oldEmailId = Session["oldEmailId"].ToString();
            userDetailViewModel editManagerDetails = new userDetailViewModel();
            {
                editManagerDetails.userId = userId;
                editManagerDetails.userName = name;
                editManagerDetails.gender = gender;
                editManagerDetails.dateOfBirth = dateOfBirth;
                editManagerDetails.address = address;
                editManagerDetails.state = state;
                editManagerDetails.city = city;
                editManagerDetails.pincode = pinCode;
                editManagerDetails.branchId = branch;
                editManagerDetails.phoneNumber = phoneNumber;
                editManagerDetails.emailId = oldEmailId;
                editManagerDetails.createdDate = DateTime.Now;
                editManagerDetails.editedDate = DateTime.Now;
                editManagerDetails.managerId = 999;
                editManagerDetails.createdBy = 999;
                editManagerDetails.editedBy = 999;
              
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:80");
                var responseTask = client.PostAsJsonAsync("BankApiNew/api/SuperManager/changeBranch?oldBranchId=" + oldBranchId + "&newBranchId="+branch,1);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {

MVCPractice/Views/Shared/_Layout.cshtml
@{

}

<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    @*<link href="~/Scripts/CSS/bootstrap-theme.css" rel="stylesheet" />*@
    <link href="~/Scripts/CSS/bootstrap.css" rel="stylesheet" />
    @*<link href="~/Scripts/CSS/site.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            console.log(Session["role"]);
            @if (Session["role"] == null) {
            }
        });
    </script>
</head>
<body>
    <div id="Navbar">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="nav" style="margin:0;padding:0;height:80px;">

            <a class="navbar-brand"><h3 style="color:#ffffff">Banking Application</h3></a>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @if (ViewContext.RouteData.Values["Controller"].ToString() != "Login")
                        {
                            <button type="button" id="homeBtn" onclick="location.href='@Url.Action("Index", "Login")'" class="btn btn-outline-light  pull-right">Home</button>
                        }
                    </li>
                </ul>
            </div>
            <div class="pull-right">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item pull-right">
    @if (Session["role"] != null)
                        {
        <a class="navbar-brand"><h4 style="color:#ffffff">Welcome @Session["userId"] !</h4></a>
                        }
    @if (Session["accountNumber"] != null)
                        {
                            string input = @Session["accountNumber"].ToString();
                            var result = "XXXXXXX" + input.Substring(input.Length - 3);
                            <a class="navbar-brand">
        <h4 style="color:#ffffff">
            @result
        </h4>
    </a>
}
    @if (Session["medal"] != null && Session["accountNumber"] != null)
                        {
                            var medal = Session["medal"].ToString() + ".jfif";
        <img src="~/Images/@medal" alt="Sample Photo" />
                        }
    <label id="HeaderName" style="color:#ffffff"></label>
    <label id="HeaderAccountNo" style="color:#ffffff"></label>
                   
                        @if (Session["role"] != null)
                        {<a class="navbar-brand"><button type="button" id="changePasswordBtn" onclick="location.href='@Url.Action("ChangePassword", "Customer")'" class="btn btn-outline-light ">ChangePassword </button><text>&nbsp;</text></a>
                        }
                   
                    
                        @if (ViewContext.RouteData.Values["Controller"].ToString() != "Login")
                        {
                          <a class="navbar-brand">  <input type="button" value="Logout" id="logoutBtn" onclick="location.href='@Url.Action("Logout", "Login")'" class="btn btn-outline-light" /></a>
                        }
                   
                </ul>
            </div>
        </nav>
    </div>
    <div id="container" class="row no-gutters">
        <div class="col-md-2 no-gutters">
            <div class="leftside bg-dark" style="height: 100vh;width:100%">
                <div class="btn-group-vertical" style="padding-left:25px;">
                    @if (Session["role"] == "Manager")
                    {
                        <button type="button" id="fundTransferBtn" onclick="location.href='@Url.Action("Withdraw","Manager")'" class="btn btn-info ">Withdraw</button><br />
    <button type="button" id="miniStatementBtn" onclick="location.href='@Url.Action("Deposit", "Manager")'" class="btn btn-info ">Deposit</button><br />
    <button type="button" id="changePasswordBtn" onclick="location.href='@Url.Action("ManageCustomer", "Manager")'" class="btn btn-info ">Customer </button><br />
    <button type="button" id="balanceEnquiryBtn" onclick="location.href='@Url.Action("Account", "Manager")'" class="btn btn-info ">Account</button><br />
                    }
                    else if (Session["role"] == "Customer" && Session["accountNumber"] != null)
                    {
                        <button type="button" id="fundTransferBtn" onclick="location.href='@Url.Action("FundTransfer","Customer")'" class="btn btn-info ">Fund Transfer</button><br />
    <button type="button" id="miniStatementBtn" onclick="location.href='@Url.Action("MiniStatement", "Customer")'" class="btn btn-info ">MiniStatement</button><br />
                    }
                    else if (Session["role"] == "BankManager")
                    {
                        <button type="button" id="Managers" onclick="location.href='@Url.Action("ManageManager","SuperManager")'" class="btn btn-info ">Managers</button><br />
                    }
                    else
                    {
                    }
                </div>
            </div>
        </div>
        <div class="col-md-10 no-gutters">
            <div class="rightside d-flex justify-content-center align-items-center" style="height:100vh; width: 100%; background-color: #c2bcbc;   ">
                @RenderBody()
            </div>
        </div>
    </div>
    <div class="modal-footer bg-dark no-gutters" style="">
    </div>
</body>
</html>

@{

}

@*<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>

    <link href="~/Scripts/CSS/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Scripts/CSS/bootstrap.css" rel="stylesheet" />
    <link href="~/Scripts/CSS/site.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark" id="nav" style="margin:0;padding:0;height:80px;">
        <div class="container-fluid" style="margin:0px;">
            <div class="navbar-header">
                <a class="navbar-brand"><h3 style="color:#ffffff">Banking Application</h3></a>
                @if (ViewContext.RouteData.Values["Controller"].ToString() != "Login")
                {
                    <button type="button" id="homeBtn" onclick="location.href='@Url.Action("Index", "Login")'" class="btn btn-outline-light  pull-right">Home</button>
                }

            </div>

            <ul class="nav navbar-nav navbar-right pull-right">
                <li class="nav-item pull-right">
                    @if (Session["role"] != null)
                    {
                        <a class="navbar-brand"><h4 style="color:#ffffff">Welcome @Session["userId"] !</h4></a>

                    }

                    @if (Session["accountNumber"] != null)
                    {
                        string input = @Session["accountNumber"].ToString();
                        var result = "XXXXXXX" + input.Substring(input.Length - 3);
                        <a class="navbar-brand">
                            <h4 style="color:#ffffff">
                                @result
                            </h4>
                        </a>

                    }
                    @if (Session["medal"] != null && Session["accountNumber"] != null)
                    {
                        var medal = Session["medal"].ToString() + ".jfif";
                        <img src="~/Images/@medal" alt="Sample Photo" />

                    }

                    <label id="HeaderName" style="color:#ffffff"></label>
                    <label id="HeaderAccountNo" style="color:#ffffff"></label>
                    @if (Session["role"] != null)
                    {<a class="navbar-brand"><button type="button" id="changePasswordBtn" onclick="location.href='@Url.Action("ChangePassword", "Customer")'" class="btn btn-outline-light ">ChangePassword </button><text>&nbsp;</text></a>
                    }


                    @if (ViewContext.RouteData.Values["Controller"].ToString() != "Login")
                    {
                        <a class="navbar-brand">  <input type="button" value="Logout" id="logoutBtn" onclick="location.href='@Url.Action("Logout", "Login")'" class="btn btn-outline-light" /></a>
                    }
                   

                </li>
            </ul>
        </div>
    </nav>
    <div class="row" style="padding:0;">
        <div class="col-md-2 bg-dark" style="width:auto;height:1000px;">

            <div class="btn-group-vertical" style="padding-left:25px;">
                <br />
                @if (Session["role"] == "Manager")
                {


                    <button type="button" id="fundTransferBtn" onclick="location.href='@Url.Action("Withdraw","Manager")'" class="btn btn-info ">Withdraw</button><br />
                    <button type="button" id="miniStatementBtn" onclick="location.href='@Url.Action("Deposit", "Manager")'" class="btn btn-info ">Deposit</button><br />
                    <button type="button" id="changePasswordBtn" onclick="location.href='@Url.Action("ManageCustomer", "Manager")'" class="btn btn-info ">Customer </button><br />
                    <button type="button" id="balanceEnquiryBtn" onclick="location.href='@Url.Action("Account", "Manager")'" class="btn btn-info ">Account</button><br />

                }
                else if (Session["role"] == "Customer" && Session["accountNumber"] != null)
                {

                      <button type="button" id="fundTransferBtn" onclick="location.href='@Url.Action("FundTransfer","Customer")'" class="btn btn-info ">Fund Transfer</button><br />
    <button type="button" id="miniStatementBtn" onclick="location.href='@Url.Action("MiniStatement", "Customer")'" class="btn btn-info ">MiniStatement</button><br />



                }
                else if (Session["role"] == "BankManager")
                {

                    <button type="button" id="Managers" onclick="location.href='@Url.Action("ManageManager","SuperManager")'" class="btn btn-info ">Managers</button><br />
                }
                else
                {

                }
            </div>
        </div>
        <div class="col-md-10 justify-content-around" style="background-color:#c2bcbc; width:100%;  text-align: center;">
            @RenderBody()
        </div>
    </div>

    <div class="modal-footer bg-dark" style="">
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            console.log(Session["role"]);
            @if (Session["role"] == null) {

            }



        });
    </script>

</body>
</html>*@