MVCPractice/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;

namespace MVCPractice.Controllers
{
    public class ManagerController : Controller
    {
        //
        // GET: /Manager/

        public ActionResult Index()
        {
            string userId = Convert.ToString(Session["userId"]);
            BankEntities2 dbContext = new BankEntities2();
            Manager manager= dbContext.Managers.Where(val=>val.userId==userId).Single<Manager>();
            List<Customer> customer = dbContext.Customers.Where(x => manager.branchId==x.branchId ).ToList<Customer>();
         
            return View(customer);
          
        }
        public ActionResult Withdraw()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Withdraw(long acc, int amt)
        {
            try
            {

                ManagerClass obj = new ManagerClass();

                string res = obj.withdraw(acc, amt);
                ViewBag.result = res;

            }

            catch (Exception exp)
            {
                ViewBag.Error = "Exception " + exp;
            }
            return View();

        }

        public ActionResult Deposit()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Deposit(long acc, int amt)
        {
            try
            {

                ManagerClass obj = new ManagerClass();

                string res = obj.deposit(acc, amt);
                ViewBag.result = res;

            }

            catch (Exception exp)
            {
                ViewBag.Error = "Exception " + exp;
            }
            return View();

        }
        public ActionResult Account()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Account(int customerId)
        {


            BankEntities2 dbContext = new BankEntities2();
            Session["customerId"] = customerId;
            string branchId = Session["Branch"].ToString();
            try
            {
                Customer allcustomer = dbContext.Customers.Single(x => x.customerId == customerId && x.branchId == branchId);
                List<Account> accounts = (dbContext.Accounts.Where(x => x.customerId == allcustomer.customerId)).ToList();
                return View("AccountsList", accounts);
            }
            catch (Exception e)
            {
                ViewBag.msg = "This is not your branch customer";
                return View("Account");
            }


        }

        public ActionResult addAccount()
        {

            return View();
        }

        public ActionResult deleteAccount()
        {
            ManagerClass obj = new ManagerClass();
            long selectedAccount = long.Parse(Session["EditedAccount"].ToString());
            obj.DeleteAccount(selectedAccount);
            return View("Account");

        }
        [HttpPost]
        public ActionResult addAccount(String AccountType, String Status, int AmountTextBox)
        {
            ManagerClass obj = new ManagerClass();
            String[] EnteredDatails = new String[7];
            EnteredDatails[0] = Session["customerId"].ToString();
            EnteredDatails[1] = AccountType;
            EnteredDatails[2] = Session["Today"].ToString();
            EnteredDatails[3] = Status;
            EnteredDatails[4] = Session["Today"].ToString();
            EnteredDatails[5] = "";
            EnteredDatails[6] = AmountTextBox.ToString();
            obj.AddAccount(EnteredDatails);

            return View();
        }
        [HttpPost]
        public ActionResult editAccount(long selectedAccount)
        {
            BankEntities2 dbContext = new BankEntities2();

            Session["EditedAccount"] = selectedAccount;
            ManagerClass obj = new ManagerClass();
            Account acc = dbContext.Accounts.Single(x => x.accountNo == selectedAccount);
            return View(acc);
        }
        [HttpPost]
        public ActionResult editAccounts(String AccountType, String Status, int amount)
        {
            ManagerClass obj = new ManagerClass();
            Account acc = new Account();
            acc.accountNo = long.Parse(Session["EditedAccount"].ToString());
            acc.accountType = AccountType;
            acc.status = Status;
            acc.dateOfEdited = Session["Today"].ToString();
            acc.ClosingDate = "";
            acc.amount = amount;
            obj.EditAccount(acc);

            return View("Account");
        }

        public ActionResult ManageCustomer()
        {
            if (TempData["deleteCustomer"] != null)
                ViewBag.deleteCustomer = TempData["deleteCustomer"].ToString();
            return View();
        }

        [HttpPost]
        public ActionResult ManageCustomer(int customerId)
        {
            BankEntities2 dbContext = new BankEntities2();
            string managerId = Session["userId"].ToString();
            Session["CustomerId"] = customerId;
            Manager mgrDetails = dbContext.Managers.Single(x => x.userId == managerId);
            Customer objCheckUser = dbContext.Customers.SingleOrDefault(x => (x.customerId == customerId));
            if (objCheckUser == null) // No customer exists
            {
                ViewBag.Error = "No customer Exists";
            }
            else
            {
                if (objCheckUser.managerId != mgrDetails.managerId)
                {
                    ViewBag.Error = "You cannot access this customer";
                }
                else
                {
                    return View(objCheckUser);
                }
            }
            ViewBag.customerId = customerId;
            return View();
        }

        public ActionResult ShowAllCustomers()
        {
            BankEntities2 dbContext = new BankEntities2();
            string managerId = Session["userId"].ToString();
            Manager mgrDetails = dbContext.Managers.Single(x => x.userId == managerId);

            List<Customer> list = dbContext.Customers.Where(x => x.managerId == mgrDetails.managerId).ToList();
            return View(list);
        }

        public ActionResult AddCustomer()
        {
            return View();
        }

        public string Encrypt(string strEncrypted)
        {
            byte[] b = System.Text.ASCIIEncoding.ASCII.GetBytes(strEncrypted);
            string encrypted = Convert.ToBase64String(b);
            return encrypted;
        }

        [HttpPost]
        public ActionResult AddCustomer(Customer custObj)
        {
            try
            {

                custObj.userId = custObj.email;
                custObj.createdDate = DateTime.Now.ToShortDateString();
                custObj.editedDate = DateTime.Now.ToShortDateString();
                //custObj.type = "Bronze";
                string managerId = Session["userId"].ToString();
                BankEntities2 dbContext = new BankEntities2();
                Manager mgrDetails = dbContext.Managers.Single(x => x.userId == managerId);
                custObj.managerId = mgrDetails.managerId;
                custObj.branchId = mgrDetails.branchId;

                ManagerClass classcustObj = new ManagerClass();
                classcustObj.addLogin(custObj.email, Encrypt("123456"), "Customer");
                int rows_affected = classcustObj.addCustomer(custObj);
                if (rows_affected == 0)
                {
                    ViewBag.Error = "Customer Not added";
                }
                else
                {
                    ModelState.Clear();
                    ViewBag.Success = "Customer Added";

                }


            }
            catch (Exception ex)
            {
                ViewBag.Error = "Exception";
            }
            return View();

        }

        public ActionResult EditCustomer()
        {
            BankEntities2 dbContext = new BankEntities2();
            int custId = int.Parse(Session["CustomerId"].ToString());
            Customer obj = dbContext.Customers.Single(x => x.customerId == custId);
            return View(obj);
        }

        [HttpPost]
        public ActionResult EditCustomer(Customer custObj)
        {
            try
            {
                custObj.customerId = int.Parse(Session["CustomerId"].ToString());
                custObj.editedDate = DateTime.Now.ToShortDateString();
                BankEntities2 dbContext = new BankEntities2();
                ManagerClass classcustObj = new ManagerClass();


                int rows_affected = classcustObj.updateCustomer(custObj);
                if (rows_affected == 0)
                {
                    ViewBag.Error = "Customer Not updated";
                }
                else
                {
                    ModelState.Clear();
                    ViewBag.Success = "Customer Editted successfully";

                }


            }
            catch (Exception ex)
            {
                ViewBag.Error = "Exception";
            }
            return View();
        }

        public ActionResult DeleteCustomer()
        {
            ManagerClass classCustObj = new ManagerClass();
            int rows_affected = classCustObj.deleteCustomer(int.Parse(Session["CustomerId"].ToString()));
            if (rows_affected == 0)
            {
                TempData.Add("deleteCustomer", "Error while deleting customer");
                //ViewBag.deleteCustomer="Error while deleting customer";
            }
            else
            {
                TempData.Add("deleteCustomer", "Customer Deleted successfully");
                ViewBag.deleteCustomer = "Customer Deleted successfully";
            }
            return RedirectToAction("ManageCustomer");
        }

    }
}

MVCPractice/Views/Manager/Account.cshtml
@model  IEnumerable<BusinessLayer.Account>
@{
    ViewBag.Title = "Account";
}
<label>@ViewBag.msg</label>

@using (Html.BeginForm("Account", "Manager"))
{
    <div class="jumbotron bg-light text-dark" style=" margin-top: 100px">
        <div>
            <h2><label id="Label1">Account</label></h2>
        </div>
        <div class="form-group">
            <label id="Label1" class="col-form-label">Customer Id</label>
            <input type="text" name="customerId" id="customerId" class="form-control" />
        </div>
        <div>
            <input type="submit" class="btn btn-outline-success" value="submit" />
        </div>
            <label></label>
    </div>

}
@*@if (Model != null)
{
    using (Html.BeginForm("editAccount", "Manager"))
    {
        <div class="jumbotron bg-light text-dark" style=" margin-top: 100px">

            <table border="2" id="Table" style="font-family:Arial" class="table table-hover table-striped">
                <tr>
                    <th> </th>
                    <th>AccountNumber</th>
                    <th>AccountType</th>
                    <th>Status</th>
                </tr>

                @foreach (BusinessLayer.Account accounts in Model)
                {
                    <tr>
                        <td>
                            @Html.RadioButton("selectedAccount", accounts.accountNo)
                        </td>
                        <td>
                            @accounts.accountNo

                        </td>
                        <td>
                            @accounts.accountType
                        </td>
                        <td>
                            @accounts.status
                        </td>
                    </tr>

                }

            </table>
            <div class="btn-group">
                <input type="submit" value="Add" id="AddButton" onclick="location.href='@Url.Action("addAccount", "Manager")'" class="btn btn-outline-success" />
                <input type="submit" value="Edit" id="EditButton" class="btn btn-outline-secondary" />
            </div>

            <Button ID="DeleteButton"  OnClick="DeleteButton_Click" Class="btn btn-outline-danger" >Delete</Button>
                </div>
                <Button ID="DeleteAccountButton"  OnClick="DeleteAccountButton_Click" Class="btn btn-outline-danger" >Click to confirm Deletion</Button>

            <label id="Label3"></label>
        </div>

    }
}*@



        

MVCPractice/Views/Manager/AccountsList.cshtml
@model  IEnumerable<BusinessLayer.Account>
@{
    ViewBag.Title = "AccountsList";
}


@using (Html.BeginForm("editAccount", "Manager"))
{
    <div class="jumbotron bg-light text-dark" style=" margin-top: 100px">
        <table border="2" id="Table" style="font-family:Arial" class="table table-hover table-striped">
            <tr>
                <th> </th>
                <th>AccountNumber</th>
                <th>AccountType</th>
                <th>Status</th>
            </tr>
            @foreach (BusinessLayer.Account accounts in Model)
            {
                <tr>
                    <td>
                        @Html.RadioButton("selectedAccount", accounts.accountNo)
                    </td>
                    <td>    
                        @accounts.accountNo
                    </td>
                    <td>
                        @accounts.accountType
                    </td>
                    <td>
                        @accounts.status
                    </td>
                </tr>
            }
        </table>
        <div class="btn-group">
            <input type="submit" value="Edit" id="EditButton" class="btn btn-outline-secondary" />
        </div>
        <input value="Add" id="AddButton" onclick="location.href='@Url.Action("addAccount", "Manager")'" class="btn btn-outline-success" />
        <label id="Label3"></label>
    </div>
}

MVCPractice/Views/Manager/AddCustomer.cshtml
@using MVCPractice.Models

@model BusinessLayer.Customer

@{
    ViewBag.Title = "AddCustomer";
}

<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>
@using (Html.BeginForm())
{
    <div class="jumbotron bg-light text-dark"  style="display: inline-block;  margin-top: 100px">
        <div>
            <h1><label id="Label1">Add Customer</label></h1>
        </div>
        <asp:Label ID="Label2" runat="server" Class="alert-info">@ViewBag.Error @ViewBag.Success</asp:Label>
        <div class="form-group">
            <label for="custName1" id="nameLabel" class="col-form-label">Name</label>
            <input type="text" name="customerName" id="customerName" class="form-control" />
            @*@Html.EditorFor(model => model.customerName)*@
        </div>
        <div class="form-group">
            <label id="genderLabel" class="col-form-label">Gender</label>
            <div @*class="form-control"*@>
                Male
                @Html.RadioButtonFor(model => model.gender, "M")
                Female
                @Html.RadioButtonFor(model => model.gender, "F")

            </div>
        </div>
        <div class="form-group">
            <asp:label id="dobLabel" class="col-form-label">Date Of birth</asp:label>
            <input type="text" name="dob" id="dob" class="form-control date-picker" />
            @*@Html.TextBox("dob", "", new { @class = "date-picker" })*@
        </div>
        <div class="form-group">
            <label id="addressLabel" class="col-form-label">Address:</label>
            <input type="text" name="address" id="address" class="form-control" />
            @*@Html.EditorFor(model => model.address)*@
        </div>
        <div class="form-group">
            <label id="stateLabel" class="col-form-label">State</label>
            @Html.DropDownList("state",
                    new SelectList(Enum.GetValues(typeof(states))),
                    "Select State",
                    new { @class = "form-control" })
        </div>
        <div class="form-group">
            <asp:label id="cityLabel" class="col-form-label">City</asp:label>
            <input type="text" name="city" id="city" class="form-control" />
            @*@Html.EditorFor(model => model.city)*@
        </div>
        <div class="form-group">
            <label id="pincodeLabel" class="col-form-label">Pincode</label>
            <input type="text" name="pincode" id="pincode" class="form-control" />
            @*@Html.EditorFor(model => model.pincode)*@
        </div>
        <div class="form-group">
            <label id="phoneNumberLabel" class="col-form-label">Phone Number</label>
            <input type="text" name="phoneNo" id="phoneNo" class="form-control" />
            @*@Html.EditorFor(model => model.phoneNo)*@
        </div>
        <div class="form-group">
            <label id="emailLabel" class="col-form-label">Email</label>
            <input type="text" name="email" id="email" class="form-control" />
            @*@Html.EditorFor(model => model.email)*@
        </div>
        <div>
            <button id="addCustomerBtn" class="btn btn-outline-dark" type="submit">Submit</button>
        </div>
    </div>
}

MVCPractice/Views/Manager/Deposit.cshtml
@model BusinessLayer.Account

@{
    ViewBag.Title = "Deposit";
}

    @using (Html.BeginForm())
{
    <div class="jumbotron bg-light text-dark">
        <div>
            <h1><label id="Label1">Deposit</label></h1>
        </div>
        <div class="form-group">
            <label id="Label2" class="col-form-label">Source Account No</label>
            <input type="text" id="acc" name="acc" class="form-control"/>
        </div>

        <div class="form-group">
            <label id="Label4" class="col-form-label">Amount</label>
            <input type="text" id="amt" name="amt" class="form-control" />
        </div>

        <div>
            <input type="submit" class="btn btn-outline-success" value="Transfer" />
        </div>
        <label id="Label6"></label>
        <div>
            @ViewBag.result
        </div>

    </div>
}

MVCPractice/Views/Manager/EditCustomer.cshtml
@using MVCPractice.Models

@model BusinessLayer.Customer

@{
    ViewBag.Title = "EditCustomer";
}

<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>
@using (Html.BeginForm())
{
    <div class="jumbotron bg-light text-dark">
        <div>
            <label><h2>Edit Customer</h2></label>
        </div>
        <asp:Label ID="Label2" runat="server" Class="alert-info">@ViewBag.Error @ViewBag.Success</asp:Label>
        <div class="input-group">
            <label for="custName1" id="nameLabel" class="col-form-label input-text-prepend">Name&nbsp;&nbsp;&nbsp;&nbsp;</label>
            <input type="text" class="form-control" name="customerName" id="customerName" />
            @*@Html.EditorFor(model => model.customerName)*@
        </div>
        <div class="input-group">
            <label id="genderLabel" class="col-form-label input-text-prepend">Gender&nbsp;&nbsp;</label>
            <div class="form-control">
                Male
                @Html.RadioButtonFor(model => model.gender, "M")
                Female
                @Html.RadioButtonFor(model => model.gender, "F")

            </div>
        </div>
        <div class="input-group">
            <asp:label id="dobLabel" class="col-form-label input-text-prepend">DOB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</asp:label>
            <input type="text" name="dob" id="dob" class="form-control date-picker"  />
            @*@Html.TextBox("dob", "", new { @class = "date-picker" })*@
        </div>
        <div class="input-group">
            <label id="addressLabel" class="col-form-label input-text-prepend">Address&nbsp;&nbsp;</label>
            <input type="text" name="address" id="address" class="form-control"/>
            @*@Html.EditorFor(model => model.address)*@
        </div>
        <div class="input-group">
            <label id="stateLabel" class="col-form-label input-text-prepend">State&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
            @Html.DropDownList("state",
                    new SelectList(Enum.GetValues(typeof(states))),
                    "Select State",
                    new { @class = "form-control" })
        </div>
        <div class="input-group">
            <asp:label id="cityLabel" class="col-form-label input-text-prepend">City&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</asp:label>
            <input type="text" name="city" id="city" class="form-control" />
            @*@Html.EditorFor(model => model.city)*@
        </div>
        <div class="input-group">
            <label id="pincodeLabel" class="col-form-label input-text-prepend">Pincode&nbsp;&nbsp;</label>
            <input type="text" name="pincode" id="pincode" class="form-control" />
            @*@Html.EditorFor(model => model.pincode)*@
        </div>
        <div class="input-group mb-3">
            <label id="phoneNumberLabel" class="col-form-label input-text-prepend">Phone Number</label>
            <input type="text" name="phoneNo" id="phoneNo" class="form-control" />
            @*@Html.EditorFor(model => model.phoneNo)*@
        </div>

        <div>
            <button id="addCustomerBtn" class="btn btn-outline-dark" type="submit">Submit</button>
        </div>
    </div>
}

MVCPractice/Views/Manager/ManageCustomer.cshtml
    @model BusinessLayer.Customer
@{
    ViewBag.Title = "ManageCustomer";
}


<div class="jumbotron bg-light text-dark">
    @ViewBag.deleteCustomer
    @using (Html.BeginForm())
    {
        <div>
            <label><h1>Manage Customer</h1></label>
        </div>
        <div class="form-group">
            <label id="Label1" class="col-form-label">Customer id </label>
            <input type="text" class="form-control" name="customerId" id="customerId" />
            @*@Html.EditorFor(model => model.customerId)*@
        </div>
        <div>
            <button type="submit" class="btn btn-outline-dark">Submit</button>
        </div>
        <label id="Label2">@ViewBag.Error</label>
        <div class="table-responsive col-10">
            @if (@Model != null)
            {
                <table border="2" style="font-family:Arial" class="table table-hover table-striped">
                    <tr>
                        <th>CustomerId</th>
                        <th>CustomerName</th>
                        <th>Gender</th>
                        <th>Date Of Birth</th>
                        <th>Address</th>
                        <th>State</th>
                        <th>City</th>
                        <th>Pincode</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Branch</th>
                    </tr>
                    <tr>
                        <td>
                            @Model.customerId
                        </td>
                        <td>
                            @Model.customerName
                        </td>
                        <td>
                            @Model.gender
                        </td>
                        <td>
                            @Model.dob
                        </td>
                        <td>
                            @Model.address
                        </td>
                        <td>
                            @Model.state
                        </td>
                        <td>
                            @Model.city
                        </td>
                        <td>
                            @Model.pincode
                        </td>
                        <td>
                            @Model.phoneNo
                        </td>
                        <td>
                            @Model.email
                        </td>
                        <td>
                            @Model.branchId
                        </td>
                    </tr>
                </table>
            }

        </div>
    }
    <div class="btn btn-group">
        @if (@Model == null)
        {
            <button id="showAllCustomersBtn" onclick="location.href='@Url.Action("ShowAllCustomers","Manager")'" class="btn btn-outline-info">Show all</button>
            <button id="add" onclick="location.href='@Url.Action("AddCustomer","Manager")'" class="btn btn-outline-success">Add</button>
        }
        else
        {

            <button id="edit" onclick="location.href='@Url.Action("EditCustomer", "Manager", new { id=@ViewBag.customerId})'" class="btn btn-outline-dark">Edit</button>
            <button id="delete" onclick="location.href='@Url.Action("DeleteCustomer","Manager", new { id=@ViewBag.customerId})'" class="btn btn-outline-danger">Delete</button>
        }

    </div>
    <label id="Label3"></label>


</div>

MVCPractice/Views/Manager/addAccount.cshtml
@{
    ViewBag.Title = "addAccount";
}

@using (Html.BeginForm())
{
    <div class="jumbotron bg-light text-dark" style=" margin-top: 100px">
        <div>
            <h1><label id="Label1">Add Account</label></h1>
        </div>
        <div class="form-group">
            <label id="AccountTypeLabel" class="col-form-label">Account Type</label>
            @{
                List<SelectListItem> listItems = new List<SelectListItem>();
                listItems.Add(new SelectListItem
                {
                    Text = "Current Account",
                    Value = "Current"
                });
                listItems.Add(new SelectListItem
                {
                    Text = "Savings Account",
                    Value = "Savings",
                    Selected = true
                });
            }
            @Html.DropDownList("AccountType", listItems, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label id="DateOfOpeneningLabel" class="col-form-label">Date Of Opening</label>
            @{
                Session["Today"] = DateTime.Now;
            }
            <label class="form-control">@Session["Today"]</label>
        </div>
        <div class="form-group">
            <label id="StatusLabel" class="col-form-label">Status</label>
            @{
                List<SelectListItem> listItems2 = new List<SelectListItem>();
                listItems2.Add(new SelectListItem
                {
                    Text = "Open",
                    Value = "Open"
                });
                listItems2.Add(new SelectListItem
                {
                    Text = "Close",
                    Value = "Close",
                    Selected = true
                });
            }
            @Html.DropDownList("Status", listItems2, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label id="DateOfEditedLabel" class="col-form-label">DateOfEdited</label>
            @{
                Session["Today"] = DateTime.Now;
            }
            <label class="form-control">@Session["Today"]</label>

        </div>
        <div class="form-group">
            <label id="ClosingDateLabel" class="col-form-label">ClosingDate</label>
            <input type="text" class="form-control" id="ClosingDateTextBox" name="ClosingDateTextBox"/>
        </div>
        <div class="form-group">
            <label id="AmountLabel" class="col-form-label">Amount</label>
            <input type="text" class="form-control" id="AmountTextBox" name="AmountTextBox" />
        </div>
        <div>
            <button id="DetailsSubmitButton" onclick="location.href='@Url.Action("Account", "Manager")'" class="btn btn-outline-secondary">Submit Details</button>
        </div>
    </div>
}

MVCPractice/Views/Manager/deleteAccount.cshtml
@model BusinessLayer.Account

@{
    ViewBag.Title = "deleteAccount";
}

MVCPractice/Views/Manager/editAccount.cshtml
@model BusinessLayer.Account 

@{
    ViewBag.Title = "editAccount";
}

<div>
    <div class="jumbotron bg-light text-dark">

        @using (Html.BeginForm("editAccounts", "Manager"))
        {
            <div >

                <label id="AccountTypeLabel" class="col-form-label">Account Type</label>
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    listItems.Add(new SelectListItem
                    {
                        Text = "Current Account",
                        Value = "Current"
                    });
                    listItems.Add(new SelectListItem
                    {
                        Text = "Savings Account",
                        Value = "Savings",
                        Selected = true
                    });
                }
                @Html.DropDownList("AccountType", listItems, new { @class = "form-control" })
            </div>
            <div  >
                <label id="DateOfOpeneningLabel" class="col-form-label">Date Of Opening</label>
                <label class="form-control">@Model.DateOfOpen</label>
            </div>
            <div  >
                <label id="StatusLabel" class="col-form-label">Status</label>
                @{
                    List<SelectListItem> listItems2 = new List<SelectListItem>();
                    listItems2.Add(new SelectListItem
                    {
                        Text = "Open",
                        Value = "Open"
                    });
                    listItems2.Add(new SelectListItem
                    {
                        Text = "Close",
                        Value = "Close",
                        Selected = true
                    });
                }
                @Html.DropDownList("Status", listItems2, new { @class = "form-control" })
            </div>
            <div  >
                <label id="DateOfEditedLabel" class="col-form-label">DateOfEdited</label>
                @{
                    Session["Today"] = DateTime.Now;
                }
                <label class="form-control">@Session["Today"]</label>
            </div>
            <div  >
                <label id="ClosingDateLabel" class="col-form-label">ClosingDate</label>
                <input type="text" name="ClosingDate" id="ClosingDate" class="form-control" />
                @*@Html.EditorFor(p => p.ClosingDate)*@
            </div>
            <div  >
                <label id="AmountLabel" class="col-form-label">Amount</label>
                <input type="text" name="amount" id="amount" class="form-control" />
                @*@Html.EditorFor(p => p.amount)*@
            </div>
            <div>
                <input type="submit" id="DetailsSubmitButton" onclick="location.href='@Url.Action("editAccounts", "Manager")'" class="btn btn-outline-secondary" />
            </div>

        }
        @using (Html.BeginForm("deleteAccount", "Manager"))
        {
            <input id="DeleteButton" value="delete" type="submit" class="btn btn-outline-danger" />
        }
    </div>

</div>